name: Bug Report
description: Report a bug in Wardrowbe
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Type
      description: How are you running Wardrowbe?
      options:
        - Docker Compose
        - Kubernetes
        - Manual/Development
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running? (git commit hash or release tag)
      placeholder: e.g., v1.0.0 or abc1234
    validations:
      required: false

  - type: dropdown
    id: ai-service
    attributes:
      label: AI Service
      description: Which AI service are you using?
      options:
        - Ollama (local)
        - OpenAI
        - Other OpenAI-compatible API
        - Not applicable
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please include relevant logs from Docker or Kubernetes.
        ```bash
        docker compose logs backend --tail 50
        docker compose logs frontend --tail 50
        docker compose logs worker --tail 50
        ```
      render: shell
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, browser console errors, etc.)
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have checked the deployment documentation
          required: false
